### ISSUE TITLE
发生崩溃

### ISSUE THREAD

**Issue by carl1990** [TheOne-Xin/presentation-sample#1]
Window type mismatch. Window Context's window type is 2037, while LayoutParams' type is set to 2038. Please create another Window Context via createWindowContext(getDisplay(), 2038, null) to add window with type:2038

**Comment by TheOne-Xin** [comment]
这个错误是说window类型不匹配，由于Android版本问题导致的。解决方案是找到app/src/main/java/com/example/presentationsample/MyPresentation.java类中的第24行，getWindow().setType(WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY);这一句中TYPE_APPLICATION_OVERLAY改为TYPE_PRESENTATION。
